base:
  sql:
    class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/"
    user-name: root
    password: admin
    db-name: mydatabase
  es-url: http://localhost:9200
  allow-endpoint:
    - "/auth/login"
    - "/v3/api-docs"
    - "/configuration/**"
    - "/swagger*/**"

#Show sql log
spring:
  jpa:
    show-sql=true
  properties:
    hibernate:
      format_sql=true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

